engula/engula

- README.md
As mentioned in #29 , we should focus on v0.2 now.
> Update the project status

- Cargo.lock
- src/engula-framework/microunit/Cargo.toml
- src/engula-framework/microunit/src/error.rs
- src/engula-framework/microunit/src/lib.rs
- src/engula-framework/microunit/src/node.rs
- src/engula-framework/microunit/src/node_server.rs
- src/engula-framework/microunit/src/unit.rs
- src/engula/Cargo.toml
- src/engula/src/hello_unit.rs
- src/engula/src/node.rs
We have an HTTP server that actually does something now :)
Start a node:
```
cargo run -p engula -- node start 127.0.0.1:8000
```
Then create a unit with `curl`:
```
curl --header "Content-Type: application/json" --request POST --data '{"kind": "hello"}' http://127.0.0.1:8000/units
```
Then list all units:
```
curl http://127.0.0.1:8000/units
```
Check https://github.com/engula/engula/pull/72/files#diff-668b2c825f579fdebdae0903e9cf9e2a7aa615af9cab7831a592b8b977f5edf9 for the programming API of microunit.
In a typical scenario, the `Unit` implementation will be a client that talks to a server in another process.
> microunit: integrate axum and implement some simple APIs

- docs/images/journal-architecture.drawio.svg
- docs/journal.md
- docs/microunit.md
- docs/storage.md
Formalize the top-level journal design.
The architecture looks like this:
> docs: add journal design document

- README.md
The original link is mostly not related to v0.2 and has been renamed to "Architecture".
> Point the roadmap to the issue

- README.md
https://engula.com returns 443 and makes this update necessary.
cc @huachaohuang
> update website address

- .github/workflows/checkcode.yml
- Cargo.lock
- src/storage/Cargo.toml
- src/storage/build.rs
- src/storage/src/grpc/bucket.rs
- src/storage/src/grpc/client.rs
- src/storage/src/grpc/error.rs
- src/storage/src/grpc/mod.rs
- src/storage/src/grpc/object.rs
- src/storage/src/grpc/proto.rs
- src/storage/src/grpc/storage.proto
- src/storage/src/grpc/storage.rs
This PR only implements the client part of the storage and leaves the server part to future PRs.
This storage uses gRPC for communications. Since the storage APIs are very simple, maybe we can find a more efficient way for RPC in the future. As long as the user interface remains the same, we will be fine.
The API design mostly follows the [Google API design guide](https://cloud.google.com/apis/design) and the [googleapis](https://github.com/googleapis/googleapis/blob/master/google/storage/v2/storage.proto), which is very nice and worth reading. However, most part of the current implementation is suboptimal in order to keep things simple for now.
> storage: add a grpc remote storage

- Cargo.lock
- Cargo.toml
- src/api/Cargo.toml
- src/api/datatypes/Cargo.toml
- src/background/Cargo.toml
- src/journal/Cargo.toml
- src/manifest/Cargo.toml
- src/microunit/Cargo.toml
- src/storage/Cargo.toml
* fix: the next release version is 0.2.0 (this fixes the warning reported by cargo audit)
* dep: update tokio to fix aduit vulnerability (this fixes the vulnerability reported newly by cargo audit)
@huachaohuang @zojw you can review this PR. It has an overlap with #99 but focuses on fixing all audit reports. It should be OK to rebase one after the other merged first. Or @zojw merge the change on "version = 0.1.0" to "version = 0.2.0" and I can close this PR as integrated in #99 .
This closes #111 .
> fix aduit vulnerability and warning

- Cargo.lock
- src/storage/Cargo.toml
- src/storage/src/grpc/mod.rs
- src/storage/src/grpc/server.rs
- src/storage/src/mem/error.rs
This is the server part of https://github.com/engula/engula/pull/98.
The server simply wraps another storage to provide a storage service.
The trait bounds in the server are very cumbersome. But at least it works for now. We can consider refactoring the trait bounds later.
> storage: implement grpc server

- Cargo.lock
- src/lib.rs
- src/microunit/Cargo.toml
- src/microunit/src/control.rs
- src/microunit/src/control_api.rs
- src/microunit/src/control_client.rs
- src/microunit/src/control_unit.rs
- src/microunit/src/error.rs
- src/microunit/src/lib.rs
- src/microunit/src/node.rs
- src/microunit/src/node_api.rs
- src/microunit/src/node_client.rs
- src/microunit/src/node_server.rs
- src/microunit/src/proto.rs
- src/microunit/src/unit.rs
- src/node.rs
This PR implements some ideas from https://github.com/engula/engula/issues/58#issuecomment-974195015 and https://github.com/engula/engula/issues/58#issuecomment-974831557.
It also implements [`IntoResponse`](https://docs.rs/axum/0.3.4/axum/response/trait.IntoResponse.html) for `Error` to convert errors to responses automatically.
We can create a control unit now. First of all, start a node:
```
> cargo run -p engula -- node start 127.0.0.1:1234
```
Then create a control unit:
```
> curl --header "Content-Type: application/json" \
--request POST \
--data '{"kind": "ControlUnit"}' \
http://127.0.0.1:1234/v1/units
```
List all units to get the address of the control unit:
```
> curl http://127.0.0.1:1234/v1/units             
[{"id":"bf099b3f-e6ba-4160-96bf-340dcf7bd048","kind":"ControlUnit", …
```
> microunit: add control unit

- .github/workflows/audit-license.yml
- .github/workflows/audit-security.yml
- .github/workflows/check-dependency.yml
- .github/workflows/checkcode.yml
- Cargo.lock
- src/platform/aws/Cargo.toml
This closes #110.
Although, installing `cargo-udeps` takes about 5 minutes. And it could provide false negative as in [this line](https://github.com/engula/engula/pull/130#discussion_r754994470).
> ci: introduce cargo-udeps 

- Cargo.lock
- src/kernel/Cargo.toml
- src/kernel/src/file/kernel.rs
- src/kernel/src/file/manifest.rs
- src/kernel/src/file/mod.rs
- src/kernel/src/lib.rs
- src/kernel/src/local/kernel.rs
- src/kernel/src/mem/mod.rs
Closes #147 .
Refactor the local kernel to hold Journal/Storage and create stream/bucket internally.
The file manifest implementation is very naive, though.
> kernel: add a file implementation

- CONTRIBUTING.md
- README.md
This closes #180.
I'm trying to elaborate the contributing guide a bit to help on answering repeating questions, while keep short to avoid pulling too much context before we have more contributors (and real-world needs).
As a result, we can still write all stuff in CONTRIBUTING file. Let's keep it concise and only introduce a folder layout later when necessary.
Brief changes:
* A copy-and-paste-able get started section
* Community principles
* How to review patches
* How to make code contribution and verify patch locally
* Licenses
> docs: elaborate the contributing guide

- .github/workflows/audit-security.yml
`cargo` already handles cache if there is one.
This closes #188.
Verified
* cache miss: https://github.com/tisonkun/engula/runs/4541804122?check_suite_focus=true
* cache hit: https://github.com/tisonkun/engula/runs/4541832408?check_suite_focus=true
> ci: always run cargo install cargo-audit

- Cargo.lock
- Cargo.toml
- src/engine/hash/Cargo.toml
- src/kernel/Cargo.toml
We need to specify package versions so that users can use a package from crates.io.
> cargo: specify package versions and update some packages

- Cargo.lock
- src/engine/luna/Cargo.toml
- src/engine/luna/src/error.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/table/block_builder.rs
- src/engine/luna/src/table/block_handle.rs
- src/engine/luna/src/table/mod.rs
- src/engine/luna/src/table/table_builder.rs
Use a simplified encoding from LevelDB/RocksDB. For example, things like prefix compression are not implemented.
> luna: add table/block builder

- Cargo.toml
- src/engine/hash/Cargo.toml
- src/journal/Cargo.toml
- src/kernel/Cargo.toml
- src/storage/Cargo.toml
- taplo.toml
- tools/ci/licenserc.yml
As discussed in https://github.com/engula/engula/issues/181, Cargo.toml style guide is not respected. `rustfmt` will support it in the future. 
As a temporary solution, we turn on some `taplo` options, including: 
- sort keys within each section (I think this is the most likely scenario)
- array auto collapse & expand.
> ci: turn on some taplo rules to format Cargo.toml

- src/kernel/src/lib.rs
- src/kernel/src/local/kernel.rs
- src/kernel/src/local/update_writer.rs
`Kernel` should create/delete the corresponding streams/buckets on receiving updates. The atomicity is not guaranteed so far.
> kernel: execute some update operations

- .github/actions/skip/action.yml
This script is needed because GitHub Actions does't support path filter for jobs and steps.
The boolean logic should be, skip CI if and only if all paths-ignore matches and none paths matches.
Previously, the default value of paths is "*", which means all paths are matched. It makes paths-ignore ("*.md", "*.svg") takes no effect.
cc @huachaohuang sorry for introducing this boolean logic bug :-(
Bug was found by [rfc: add signle write journal CI #14](https://github.com/engula/engula/runs/4762098913?check_suite_focus=true) where only "*.md" modified but "test" job runs.
Fixes verified by:
* [edit toml](https://github.com/tisonkun/engula/actions/runs/1678010370)
* [edit md](https://github.com/tisonkun/engula/actions/runs/1678009419)
> ci: fix boolean logic

- src/journal/src/local/mem/journal.rs
- src/journal/src/local/mem/mod.rs
- src/journal/src/stream.rs
- src/kernel/src/kernel.rs
- src/kernel/src/lib.rs
- src/kernel/src/local/update_writer.rs
* `seek` and `truncate` should handle invalid argument:
* otherwise, `seek` to a truncated sequence and read will return from the current very beginning event, it's not the one on the seek sequence.
* otherwise, `truncate` a future sequence is noop but you can still append to arrive that sequence so that `truncate`'s semantic doesn't hold.
* `seek` becomes zero-based (seek_to_inclusive) so that we don't have to `+ 1` everywhere.
* `wait_next` is reimplemented, I hope the code more sane.
cc @huachaohuang @w41ter-l
> journal: refactor event stream

- docs/rfcs/00000000-template.md
The template is mostly derived from [Rust](https://github.com/rust-lang/rfcs/blob/master/0000-template.md).
> docs: update the rfc template

- Cargo.lock
- src/journal/Cargo.toml
- src/journal/build.rs
- src/journal/src/remote/shared/mod.rs
- src/journal/src/remote/shared/proto/mod.rs
- src/journal/src/remote/shared/proto/server.proto
- src/journal/src/remote/shared/server/mod.rs
This PR closes #325.
Only the basic interface, methods and fields are defined, and the rest will be defined when needed.
> journal: add basic defination of shared journal server

- src/engine/luna/src/memtable.rs
- src/engine/luna/src/merging_scanner.rs
In the previous implementation, invalid scanners come first in `MergingScanner` because of the `Reverse` wrapper. This PR introduces a dedicated wrapper to order scanners for `MergingScanner`.
> luna: fix MergingScanner

- .github/workflows/ci.yml
- Cargo.lock
- rust-toolchain.toml
- src/storage/Cargo.toml
so that we don't have to clone the whole git repo for dependencies.
cc @zojw
> replace git dep to crates dep

- Cargo.lock
- Cargo.toml
- src/object-engine/client/Cargo.toml
- src/object-engine/client/src/engine.rs
- src/object-engine/client/src/error.rs
- src/object-engine/client/src/lib.rs
- src/object-engine/client/src/master.rs
- src/object-engine/client/src/tenant.rs
- src/object-engine/proto/Cargo.toml
- src/object-engine/proto/build.rs
- src/object-engine/proto/proto/master.proto
- src/object-engine/proto/src/lib.rs
Closes #416 
Basically identical to https://github.com/engula/engula/pull/413.
> object-engine: add basic client interfaces

- .cargo/audit.toml
- .github/workflows/ci.yml
Remove .cargo/audit.toml as we don't depend on chrono anymore and thus we don't have to ignore it anymore.
Replace manually settings up editorconfig checker with an existing gha.
> ci: tidy ci settings

- CONTRIBUTING.md
https://stackoverflow.com/a/3796947/12815325.
This steps miss in contributing.md. `cargo build` may fail if not init the submodule.
> doc: add submodule init steps in CONTRIBUTING.md

- Cargo.lock
- src/engula/Cargo.toml
- src/engula/src/main.rs
- src/engula/src/server.rs
This closes #466.
Other logging points can be added along with development.
I don't find a callback point to prompt when the service is ready. If you know how to achieve it, please comment.
BTW, I'll try to add a health check service for the some purpose in another aspect (and programatic for e2e tests).
> Introduce logging support

- src/object-engine/client/src/bucket.rs
- src/object-engine/client/src/engine.rs
- src/object-engine/client/src/tenant.rs
- src/object-engine/master/proto/bucket.proto
- src/object-engine/master/proto/tenant.proto
- src/object-engine/master/src/master.rs
- src/object-engine/master/src/server.rs
Simplifies RPC interactions between components.
> object-engine/master: use tenant/bucket names as unique indentifiers

- Cargo.lock
Signed-off-by: Chojan Shang <psiace@outlook.com>
- dependencies: bump regex to 1.5.5, make audit happy
Fixes: #577
> dependencies: bump regex to 1.5.5, make audit happy

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
This closes #582.
You can see the result at [the fork repo](https://github.com/tisonkun/engula/issues/new/choose).
I think sooner or later we should add an entry for "New Feature", but I don't find a good workflow for them as we don't use it yet actually. So I keep "blank_issues_enabled: true" and postpone how we issue a new feature later.
cc @huachaohuang @w41ter-l @PsiACE
cc @jackwener these templates learn a lot from those of Apache Doris (Incubating).
> Add issue templates 

- Cargo.lock
- src/engula/client/Cargo.toml
- src/engula/client/src/v1/client.rs
- src/engula/client/src/v1/collection.rs
- src/engula/client/src/v1/database.rs
- src/engula/client/src/v1/error.rs
- src/engula/client/src/v1/mod.rs
- src/engula/client/src/v1/universe.rs
Closes #584 
The v1 code is not used for now and will replace the existing client implementation when it is ready.
> engula/client: implement some of the new APIs

- Cargo.lock
- src/object-engine/lsmstore/Cargo.toml
- src/object-engine/lsmstore/build.rs
- src/object-engine/lsmstore/proto/manifest.proto
- src/object-engine/lsmstore/src/store.rs
- src/object-engine/lsmstore/src/versions/manifest.rs
- src/object-engine/lsmstore/src/versions/mod.rs
- src/object-engine/lsmstore/src/versions/proto.rs
- src/object-engine/lsmstore/src/versions/version.rs
- src/object-engine/lsmstore/src/versions/version_set.rs
ref #556 's first task
Implement a local disk-based manifest that will be used in lsmstore
> object-engine: add local manifest for lsmstore

- src/object-engine/filestore/src/lib.rs
- src/object-engine/filestore/src/store.rs
- src/object-engine/lsmstore/proto/manifest.proto
- src/object-engine/lsmstore/src/iterator/level_iter.rs
- src/object-engine/lsmstore/src/iterator/manifest_iter.rs
- src/object-engine/lsmstore/src/iterator/merging_iter.rs
- src/object-engine/lsmstore/src/iterator/mod.rs
- src/object-engine/lsmstore/src/lib.rs
- src/object-engine/lsmstore/src/store.rs
- src/object-engine/lsmstore/src/table/mod.rs
- src/object-engine/lsmstore/src/table/table_reader.rs
- src/object-engine/lsmstore/src/versions/mod.rs
- src/object-engine/lsmstore/src/versions/version.rs
- src/object-engine/lsmstore/src/versions/version_set.rs
ref #556
Implements some iterators for lsm store
- `manifest_iter` to iterate between manifest files in a level
- `level_iter` to iterate sst file in a level by combinate `manifest_iter` and `table_iter`
- `merging_iter` to merge multiple levels result
full usage can be seen in  https://github.com/engula/engula/compare/main...zojw:lsm-rw?expand=1#diff-1593cd134f18c1abca6d47b743a8990e901854c3cdda77454ea77ce0b0e9a017R42
> object-engine: implement iterators in lsmstore

- src/server/src/cmd/get.rs
- src/server/src/cmd/mod.rs
- src/server/src/cmd/ping.rs
- src/server/src/error.rs
- src/server/src/lib.rs
- src/server/src/mio/connection.rs
- src/server/src/uio/connection.rs
```
$ redis-cli -p 21716
127.0.0.1:21716> get k k
(error) ERR wrong number of arguments for 'get' command
127.0.0.1:21716> ping 42
"42"
127.0.0.1:21716> ping 42 43
(error) ERR wrong number of arguments for 'ping' command
127.0.0.1:21716> 
```
> fix: wrong number of arguments should not let server crash

- Cargo.lock
- src/bin/Cargo.toml
- src/bin/src/argenum.rs
- src/bin/src/server.rs
- src/server/Cargo.toml
- src/server/src/config.rs
- src/server/src/lib.rs
This closes #663.
cc @huachaohuang @w41ter @zojw 
Two design decisions are made here:
1. Configs from args or file can be present together. We prefer those from args to those from file.
2. Thus, we should detect whether a config is passed from args, so the default value of args cannot set. Otherwise we don't know it's configured by default or by users.
Code for parsing the toml file can be refactor if we grow our configs.
> feat: config from file 

- Cargo.lock
- src/bin/src/server.rs
- src/engine/Cargo.toml
- src/engine/src/alloc/mod.rs
- src/engine/src/db.rs
- src/engine/src/diskcache/mod.rs
- src/engine/src/diskcache/store.rs
- src/engine/src/key_space.rs
- src/engine/src/lib.rs
- src/engine/src/objects/mod.rs
- src/engine/src/record.rs
- src/server/src/cmd/cmd_des.rs
- src/server/src/cmd/command.rs
- src/server/src/cmd/del.rs
- src/server/src/cmd/get.rs
- src/server/src/cmd/info.rs
- src/server/src/cmd/ping.rs
- src/server/src/cmd/set.rs
- src/server/src/cmd/unknown.rs
- src/server/src/config.rs
- src/server/src/lib.rs
- src/server/src/server.rs
Example of `config.toml`:
```toml
max_memory=134217728
root="/tmp/disk-cache"
[disk_opts]
mem_capacity=134217728
file_size=33554432
disk_capacity=1073741824
write_buffer_size=67108864
```
> engine: evict key and save to disk cache

- src/api/engula/server/v1/error.proto
- src/api/engula/server/v1/node.proto
- src/api/src/lib.rs
- src/server/src/bootstrap.rs
- src/server/src/error.rs
- src/server/src/node/replica/mod.rs
- src/server/src/service/node.rs
This PR closes #707.
I added a structured error message for transporting detailed errors in RPC.
There are two ways to use it:
1. Combine with `grpc-status-details-bin`, for example, use `tonic::Status::with_details` to build, set the code to `Code::Unknown`, so that the client can extract detail from it and deserialize it as `Error`.
2. Add an `Error` field to `GroupResponse`, so that `BatchResponse` is always successful, and each `GroupResponse` can have separate error message; at the same time, even if a group request is successfully executed, `Error` message can also be carried in `GroupResponse`, such as follower read request returns the `ReplicaDesc` of the leader.
> api: add structured error message

- Cargo.lock
- src/client/Cargo.toml
- src/client/src/lib.rs
- src/client/src/node_client.rs
This refers to #710.
This patch brings a basic implementation of `node_client`.
~~There is an open question about whether we should use a dedicated method for create shard (https://github.com/engula/engula/pull/709#discussion_r886779559).~~ Resolved.
Also, I'm unsure how to testing via bootstrap a cluster and fulfill kv pairs yet. @w41ter you may use this patch to write some liveness and get/put tests.
> client: add node_client 

- Cargo.lock
- src/api/Cargo.toml
- src/api/engula/server/v1/error.proto
- src/api/engula/server/v1/node.proto
- src/api/engula/server/v1/root.proto
- src/api/src/lib.rs
- src/client/src/node_client.rs
- src/server/src/bootstrap.rs
- src/server/src/error.rs
- src/server/src/node/mod.rs
- src/server/src/node/state_engine.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/src/root/store.rs
- src/server/src/service/node.rs
- src/server/src/service/root.rs
closes #730
Support `get_root` on node service
1. First bootstrap  node, save itself as root node in its state_engine
2. Other join bootstrap node, save join response's  root nodes in state_engine
3. Root leader broadcast root nodes(and first element is current leader) to all known recent nodes periodically
4. Node handles heartbeat and update root info in memory + state_engine
6. Client should call get_node and try first element(high probability as current root leader)
7. Root service method should return NotRoot error with its known root
The node power-off long time and all its known root nodes have dead maybe not work until recieve root hearbeat
> node: support get_root

- src/api/engula/server/v1/root.proto
- src/server/src/bootstrap.rs
- src/server/src/service/root.rs
This filed was introduced in #718, it aims to prevent nodes that do not belong to the target cluster from being added to the cluster.
In the previous PRs(https://github.com/engula/engula/pull/731#discussion_r892999362, https://github.com/engula/engula/pull/737#discussion_r893666728), I found that this code does not actually execute, because each Node will only successfully call `join` once, and save the cluster id. Once successful, no subsequent `join` request will be issued.
This field was added to `JoinNodeRequest` by mistake, so I removed it. For its purpose, there should be a separate RPC (or adding a `cluster_id` field on the key RPC requests) to confirm that the cluster id matches.
> api,server: remove cluster_id in JoinNodeRequest

- src/server/src/error.rs
- src/server/src/node/job/destory_replica.rs
- src/server/src/node/job/mod.rs
- src/server/src/node/job/report_state.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/node/replica/mod.rs
- src/server/src/node/replica/raft/node.rs
- src/server/src/node/replica/raft/worker.rs
- src/server/src/service/root.rs
This PR closes #744.
This PR uses `StateObserver` and `DescObserver` to subscribe to `ReplicaState` and `GroupDesc` changes from raft and fsm respectively. Also added `StateChannel` for broadcasting these changes. 
A worker is added to listen to the `StateChannel` and sends these changes to the root servers.
> server: report replica state and group descriptor changes

- src/api/engula/server/v1/node.proto
- src/client/src/node_client.rs
- src/server/src/node/replica/eval/cmd_batch_write.rs
- src/server/src/node/replica/eval/cmd_delete.rs
- src/server/src/node/replica/eval/cmd_get.rs
- src/server/src/node/replica/eval/cmd_put.rs
- src/server/src/node/replica/mod.rs
- src/server/src/root/schema.rs
- src/server/src/root/store.rs
This PR closes #750.
This PR removes the `shard_id` field in `GroupRequest` and adds `Shard{Get,Put,Delete}Request`, so `BatchWriteRequest` can support `put` and `delete` of different shards.
FYI @zojw
> api,client,server: support batch writes across shards within a group

- src/api/engula/server/v1/node.proto
- src/server/src/bootstrap.rs
- src/server/src/node/engine/group.rs
- src/server/src/node/replica/eval/cmd_prefix_list.rs
- src/server/src/node/replica/eval/mod.rs
- src/server/src/node/replica/fsm/checkpoint.rs
- src/server/src/node/replica/mod.rs
- src/server/src/node/replica/retry.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/src/root/store.rs
- src/server/tests/group_test.rs
as pre-step of #766, it makes collections in `__system__` as "one init-shard per collection" and support list values in the collection(it also assumes that `__system__` database's shard doesn't need auto split)
closes #773
> root: save system db as "one shard per collection" & support list system collection

- src/server/src/node/engine/group.rs
- src/server/src/raftgroup/mod.rs
- src/server/src/raftgroup/storage.rs
- src/server/src/root/job.rs
- src/server/src/service/raft.rs
- src/server/tests/group_test.rs
- src/server/tests/helper/client.rs
The underlying `raft-rs` crate isn't allow empty configs enter joint state, so have to add replicas one by one.
> server: fix initialize raft group

- src/server/src/node/mod.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/policy_leader_cnt.rs
- src/server/src/root/allocator/policy_replica_cnt.rs
- src/server/src/root/allocator/policy_shard_cnt.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/allocator/source.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
closes #814
rough implement only takes care the opportunity that transfer between existing replicas 
```
----------
node replicas: 2 -> [2, 15, 5, 11, 8]
node replicas: 4 -> [13, 4, 10, 16]
node replicas: 1 -> [1, 14, 7, 18]
node replicas: 3 -> [3, 6, 12, 9, 17]
group shards: 2 -> [2, 6]
group shards: 4 -> [5, 9]
group shards: 3 -> [3, 7]
group shards: 6 -> [4]
group shards: 5 -> [1]
group shards: 1 -> [8]
cluster_nodes: [1, 2, 3, 4]
node group leader: 1 -> [1, 3]
node group leader: 4 -> [6, 5, 2, 4]
----------
10. try balance leader between nodes
transfer group 1 leader from 1 to 3
transfer group 5 leader from 4 to 2
----------
node replicas: 2 -> [2, 15, 5, 11, 8]
node replicas: 4 -> [13, 4, 10, 16]
node replicas: 1 -> [1, 14, 7, 18]
node replicas: 3 -> [3, 6, 12, 9, 17]
group shards: 2 …
```
> root: support rebalance leader

- Cargo.lock
- src/server/Cargo.toml
- src/server/src/bootstrap.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/state.rs
- src/server/src/root/allocator/policy_leader_cnt.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/src/service/admin/metadata.rs
closes #835
all in one API, it recommends using [jq](https://stedolan.github.io/jq/) to filter detailed data
```shell
curl -s  http://localhost:21805/admin/metadata | jq '.'
```
```json
{
"databases": [
{
"collections": [
{
"id": 1,
"mode": "range",
"name": "collection"
},
{
"id": 2,
"mode": "range",
"name": "database"
},
{
"id": 5,
"mode": "range",
"name": "group"
},
{
"id": 3,
"mode": "range",
"name": "meta"
},
{
"id": 4,
"mode": "range",
"name": "node"
},
{
"id": 6,
"mode": "range",
"name": "replica_state"
}
],
"id": 1,
"name": "__system__"
},
{
"collections": [
{
"id": 7,
"mode": "hash(3)",
"name": "test_co"
}
],
"id": 2,
"name": "test_db"
}
],
"groups": [
{
"epoch": 7,
"id": 0,
"replicas": [
{
"id": 1,
"node": 0,
"raft_role": 2,
"replica_role": 0,
"term": 3
}
],
"shards": [
{ …
```
> root: export root info via http api

- src/bin/src/main.rs
- src/server/src/bootstrap.rs
- src/server/src/lib.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/mod.rs
- src/server/tests/bootstrap_test.rs
- src/server/tests/group_test.rs
- src/server/tests/helper/context.rs
- src/server/tests/migration_test.rs
Support disable auto rebalance via allocator config in the unit test.
For example, if we want to test & assert shard migration results, disabling shard balance can stabilize our shard location assertion
https://github.com/engula/engula/runs/7313890135?check_suite_focus=true
> test: support disable auto balance in unit test

- src/api/engula/server/v1/error.proto
- src/api/engula/server/v1/metadata.proto
- src/api/engula/server/v1/node.proto
- src/api/engula/server/v1/root.proto
- src/api/src/error.rs
- src/client/src/node_client.rs
- src/client/src/root_client.rs
- src/server/proto/v1/metadata.proto
- src/server/src/bootstrap.rs
- src/server/src/error.rs
- src/server/src/node/engine/state.rs
- src/server/src/node/job/report_state.rs
- src/server/src/node/mod.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/src/service/node.rs
- src/server/src/service/root.rs
This is the leading PR of root service discovery of #846. The epoch number is added to the return value of the `get_root` rpc, which is used to determine the old and new root desc, so that the client can judge which node's root list is more freshness, so as to achieve a convergence state.
> *: add root group epoch for RootDesc

- src/api/engula/server/v1/metadata.proto
- src/server/src/node/replica/state.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/policy_leader_cnt.rs
- src/server/src/root/allocator/policy_replica_cnt.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/allocator/source.rs
- src/server/src/root/job.rs
- src/server/src/root/liveness.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
1. avoid moving or advising replica to the node that already contains replica(even if the one that does not include in group_desc)
ref #856, this can relieve the recreating replica problem
3.  avoid useless drop root leader
turn off a normal node shouldn't observe drop leader log in root leader node.
4. add rough root liveness
closes #861, we can observe allocate stop trying to reallocate replica or transfer leader to offline-node after 1 min.
5. send heartbeat parallel
but slow reconcile still can cause inaccurate heartbeat interval, but it can be solve in next PR(add scheduler to async execute task)
> root: refine root allocator 

- src/server/src/root/allocator/mod.rs
- src/server/src/root/schedule.rs
Fix a mistake introduced by previous refactor #888
For example, if we want to allocate 16 groups, the last group task will try to create wrong 16 replicas
> root: fix wrong group inital replica count

- src/server/src/node/replica/migrate.rs
- src/server/src/node/replica/state.rs
- src/server/tests/helper/client.rs
- src/server/tests/migration_test.rs
This PR fixs a problem which find during fix #889, the source group of migration should keep idempotency of `migrate` RPC method.
> server: migration step retry

- Cargo.lock
- src/bin/Cargo.toml
- src/bin/src/main.rs
Tracing's default output is colorized tokio-rs/tracing#1160, it makes us hard to grep structured log(e.g. `fgrep 'group=xx' d1.log` get nothing)
It's better to turn it off when we redirect stdout/stderr to file(usually both, `RUST_LOG=INFO cargo run start --init --db d1 &> d1.log`).
> *: disable tracing colorized output if not tty

- src/server/src/service/admin/health.rs
- src/server/src/service/admin/metadata.rs
- src/server/src/service/admin/metrics.rs
- src/server/src/service/admin/mod.rs
- src/server/src/service/admin/service.rs
redirect the client to root when the access node is not root.
this can test with `curl -L` and make easier to test when root change
> root: support access /admin/metadata http api in not-root node

- src/server/src/root/job.rs
- src/server/src/root/liveness.rs
- src/server/src/root/mod.rs
closes #905
just add init liveness record when heartbeat fail and no exist liveness record, the node will be judged as offline after liveness-threshold passed
> root: fix unaccess success node be judged as online

- src/server/src/root/job.rs
- src/server/src/root/metrics.rs
- src/server/src/root/mod.rs
- src/server/src/root/schedule.rs
- src/server/src/root/schema.rs
- src/server/src/root/watch.rs
ref #834
This PR try to add metric related with root process, like: bootstrap, reconcile, heartbeat and watch
It should be a follow-up PR to push current cluster info summary(like: node, group, replica, shard.. as metric)
> root: add root process metrics

- src/server/src/root/collector.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/service/admin/metadata.rs
- src/server/src/service/admin/metrics.rs
- src/server/src/service/admin/mod.rs
ref #834, Add root info collector(effect on root leader),  so we can observe the node/group/replica/shard/leader count from metrics
```
curl -Ls  http://localhost:21805/admin/metrics | grep cluster_
cluster_group_shard_total{group="0"} 6
cluster_group_shard_total{group="1"} 0
cluster_group_shard_total{group="10"} 0
cluster_group_shard_total{group="11"} 0
cluster_group_shard_total{group="12"} 1
cluster_group_shard_total{group="13"} 0
cluster_group_shard_total{group="14"} 0
cluster_group_shard_total{group="15"} 0
cluster_group_shard_total{group="16"} 0
cluster_group_shard_total{group="17"} 0
cluster_group_shard_total{group="18"} 1
cluster_group_shard_total{group="2"} 0
cluster_group_shard_total{group="3"} 0
cluster_group_shard_total{group="4"} 0
cluster_group_shard_total{group="5"} 0 …
```
> root: add root info collector

- src/server/src/error.rs
- src/server/src/root/allocator/policy_leader_cnt.rs
- src/server/src/root/schedule.rs
fixes #945
Previously, the root reconcile scheduler headlessly threw fake group_not_found to let outer retry & wait for the new update.
But this temporary logic will lead to a mistake like #945, this PR try to refine them.
Currently, reconcile workflow is 1. allocator finds & enqueue task, 2. scheduler consumes task queue and executes the actual task
There is a time interval between "create task" and "execute task", so when we found something in the task mismatched with real cluster info(e.g. task has a group, but the real cluster doesn't) normally it indicate task's info is outdated, so it chooses to abort the task(allocator should recreate task if it's a real need).
> root: refine info not_found handle in reconcile scheduler

- src/client/src/group_client.rs
During w41ter testing, we observe a similar problem like #945, but cause by epoch_not_match~
Turn on accurate_epoch could let group_client retry for this error( and it seems no other caller need accurate_epoch=false behavior, so this PR change it directly
```
2022-08-03T11:17:11.049432Z  INFO engula_server::root::schedule: handle reconcile task task=ReconcileTask { task: Some(TransferGroupLeader(TransferGroupLeaderTask { group: 7, target_replica: 179, src_node: 2, dest_node: 3 })) }
2022-08-03T11:17:11.052940Z ERROR engula_server::root::schedule: transfer group leader fail group=7 dest_replica=179 err=EpochNotMatch(GroupDesc { id: 0, epoch: 0, shards: [], replicas: [] })
2022-08-03T11:17:11.052987Z  INFO engula_server::root::schedule: handle reconcile task task=ReconcileTask { task: …
```
> client: turn on epoch_not_match retry for move leader and shard

- src/server/proto/v1/schedule.proto
- src/server/src/bootstrap.rs
- src/server/src/root/bg_job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schedule.rs
- src/server/src/root/schema.rs
- src/server/src/service/admin/job.rs
- src/server/src/service/admin/mod.rs
- src/server/tests/admin_test.rs
move `create_collection` task to the new persist `bg_job` module(it should be renamed to `job` in the following PR), it will:
- setup two new internal collections: "job" and "history_job" to persist job
- spawn a new task to handle jobs in collections
- tmp add a new "/job" API  to diagnose
after this PR, create_collection can be executed event shutdown all nodes (it's still some question about idempotent problem about create_shard and remove_shard operation should be refine in later)
> root: persist create_collection job

- conf/default.toml
- src/bin/src/main.rs
- src/server/src/bootstrap.rs
- src/server/src/lib.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/tests/helper/context.rs
- src/server/tests/node_schedule_test.rs
Before this PR, root setup one group per "cpu_core / group-replica-cnt", this makes some cores cannot be used
(e.g. 2c x 3 clusters can only set up 2 groups and one node can be observed as no requests)
This PR change strategy to “one group per cpu_core".
By the way, it also adds a new config item "cpu_nums" to help test multiple processes on a single node in test env.
> In production env, multiple processes on a single node should bind cpu_core(taskset or numactl), engula can auto-detect the bound cpu_core, so normally, it also no need to configure "cpu_nums" in production env
> root: setup group per cpu_core

- Cargo.lock
- src/bin/Cargo.toml
- src/bin/bench/Cargo.toml
It fixs `expected an signed 64 bit or less integer for key` reported by config-rs.
> bin: upgrade config-rs to v0.13.2

- src/client/src/app_client.rs
- src/client/src/group_client.rs
- src/client/src/migrate_client.rs
- src/client/src/shard_client.rs
- src/server/src/root/bg_job.rs
- src/server/src/root/schedule.rs
- src/server/tests/helper/client.rs
- src/server/tests/helper/context.rs
- src/server/tests/helper/socket.rs
- src/server/tests/migration_test.rs
Refreshing the group state may get the updated group desc, and some requests, such as `ShardGetRequest`, require the epoch to be the same as when the `GroupClient` was created, otherwise a `ShardNotFound` error will returned.
> client: avoid refreshing group state

- scripts/bootstrap.sh
- src/server/src/lib.rs
- src/server/src/node/engine/group.rs
- src/server/src/node/engine/mod.rs
- src/server/src/node/replica/fsm/checkpoint.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/raftgroup/applier.rs
- src/server/src/raftgroup/fsm.rs
- src/server/src/raftgroup/node.rs
- src/server/src/serverpb.rs
rocksdb::Write takes a long time, so use the plug mechanism to save a batch of log entries into a write batch to reduce the overhead of rocksdb::Write.
> server: fsm support plug & group commit

- src/server/src/root/allocator/policy_replica_cnt.rs
avoid balancer chooses to move the unpromoted group's replica
> root: avoid move unpromoted group replicas

- src/server/src/node/mod.rs
- src/server/src/node/replica/mod.rs
- src/server/src/node/replica/retry.rs
- src/server/src/root/store.rs
- src/server/src/service/node.rs
1. avoid unnecessary spawn if group has only 1 request
2. reduce upvars size of generator
> server: reduce execute group request overhead

- Cargo.lock
rust-rocksdb does not apply -DROCKSDB_RANGESYNC_PRESENT and -DROCKSDB_FALLOCATE_PRESENT, this PR add it.
> *: upgrade rust-rocksdb

- src/server/src/bootstrap.rs
- src/server/src/config.rs
- src/server/src/lib.rs
- src/server/src/node/engine/group.rs
- src/server/src/node/engine/mod.rs
- src/server/src/node/engine/state.rs
- src/server/src/node/job/destory_replica.rs
- src/server/src/node/mod.rs
When cf was created before, the default configuration was used. Now options are set to the options exported by config.
> server: set cf options from config

- Cargo.lock
- src/client/Cargo.toml
- src/client/src/group_client.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/migrate.rs
fix blocked on recreating pull stream
also, add an additional leader check before the return stream in the node
> client: fix blocked on recreate pull stream
