- .github/workflows/checkcode.yml
> Enable workflow when PR

- .github/workflows/checkcode.yml
- Cargo.lock
- engula/Cargo.toml
- engula/src/format/bloom_filter.rs
- engula/src/format/format.proto
- engula/src/format/mod.rs
> Add BloomFilter

- .github/workflows/checkcode.yml
> simplify workflow trigger strategy

- README.md
- engula/examples/hello.rs
> add outputs for example

- README.md
- engula/examples/hello.rs
Follow up to #21 .
cc @huachaohuang 
Sorry for this follow up. If we take warnings seriously, we can [require the workflow](https://docs.gearset.com/en/articles/2437757-managing-status-check-rules-in-github) before merging.
> fix cargo fmt warnings

- .github/workflows/checkcode.yml
> Remove branch filter on workflow trigger strategy

- Cargo.lock
- src/engula-kernel/Cargo.toml
- src/engula-kernel/background/Cargo.toml
- src/engula-kernel/background/src/error.rs
- src/engula-kernel/background/src/job_builder.rs
- src/engula-kernel/background/src/job_runtime.rs
- src/engula-kernel/background/src/lib.rs
> kernel/background: add some basic structs

- Cargo.lock
- Cargo.toml
- src/engula-framework/Cargo.toml
- src/engula-framework/microunit/Cargo.toml
- src/engula-framework/microunit/src/error.rs
- src/engula-framework/microunit/src/lib.rs
- src/engula-framework/microunit/src/node.rs
- src/engula-framework/microunit/src/node_server.rs
- src/engula-framework/microunit/src/unit.rs
- src/engula-framework/src/lib.rs
- src/engula/Cargo.toml
- src/engula/src/node.rs
Wow, we have a runnable binary with this PR :)
```
USAGE:
engula node start <ADDR>
```
> framework/microunit: add some basic structs

- .github/workflows/audit-security.yml
Add basic security audit ci. Powered by cargo-audit.
Signed-off-by: Chojan Shang <psiace@outlook.com>
> ci: add security audit

- Cargo.lock
- Cargo.toml
- src/engula-api/Cargo.toml
- src/engula-api/datatypes/Cargo.toml
- src/engula-api/datatypes/src/hash_map.rs
- src/engula-api/datatypes/src/int64.rs
- src/engula-api/datatypes/src/lib.rs
- src/engula-api/datatypes/src/list.rs
- src/engula-api/src/lib.rs
- src/engula/Cargo.toml
Add some code to demonstrate some ideas described in https://github.com/engula/engula/discussions/55.
> api: add some basic data types

- docs/images/storage-architecture.drawio.svg
- docs/storage.md
Formalize the top-level design of Storage.
> docs: add storage design document

- .github/workflows/checkcode.yml
This closes #101 .
cc @huachaohuang
> ci: run cargo test with --workspace

- src/journal/src/journal.rs
- src/journal/src/lib.rs
- src/journal/src/mem/journal.rs
- src/journal/src/mem/stream.rs
- src/journal/src/stream.rs
> journal: make timestamp generic

- .github/workflows/checkcode.yml
- CONTRIBUTING.md
- rust-toolchain.toml
**Summary**
- toolchain: add components
- ci: add run clippy with --tests
- docs: update the contributing doc
**Related**
Fixes #105
> ci: add run clippy with --tests

- src/storage/src/bucket.rs
- src/storage/src/grpc/bucket.rs
- src/storage/src/grpc/client.rs
- src/storage/src/grpc/error.rs
- src/storage/src/grpc/mod.rs
- src/storage/src/grpc/object.rs
- src/storage/src/grpc/storage.proto
- src/storage/src/grpc/storage.rs
- src/storage/src/lib.rs
- src/storage/src/mem/bucket.rs
- src/storage/src/mem/error.rs
- src/storage/src/mem/mod.rs
- src/storage/src/mem/object.rs
- src/storage/src/mem/storage.rs
- src/storage/src/object.rs
- src/storage/src/storage.rs
Refactor storage traits in a way similar to https://github.com/engula/engula/pull/107.
This PR also remove the list API temporarily to simplify things for now.
> storage: refactor traits and implementations

- src/journal/src/grpc/error.rs
This is a follow up to #119.
Try to keep code tidy.
> journal: tidy errors

- Cargo.lock
- Cargo.toml
- src/journal/Cargo.toml
- src/journal/src/error.rs
- src/journal/src/journal.rs
- src/journal/src/lib.rs
- src/journal/src/mem/journal.rs
- src/journal/src/mem/mod.rs
- src/journal/src/mem/stream.rs
- src/journal/src/stream.rs
- src/lib.rs
Check https://github.com/engula/engula/pull/143 for example usage of Journal.
> journal: cleanup traits for v0.2

- Cargo.lock
- src/journal/Cargo.toml
- src/journal/src/grpc/error.rs
- src/journal/src/grpc/mod.rs
- src/journal/src/grpc/proto.rs
- src/journal/src/grpc/server.rs
- src/journal/src/grpc/stream.rs
- src/journal/src/stream.rs
This is a follow-up to https://github.com/engula/engula/pull/158#discussion_r761622075.
> journal: simplify serde for Timestamp

- src/kernel/build.rs
- src/kernel/src/error.rs
- src/kernel/src/grpc/client.rs
- src/kernel/src/grpc/error.rs
- src/kernel/src/grpc/kernel.proto
- src/kernel/src/grpc/kernel.rs
- src/kernel/src/grpc/mod.rs
- src/kernel/src/grpc/proto.rs
- src/kernel/src/grpc/server.rs
- src/kernel/src/lib.rs
- src/kernel/src/mem/mod.rs
- src/kernel/src/metadata.rs
- src/storage/src/grpc/mod.rs
> kernel: add gRPC kernel client and server

- .github/actions/cargo-cache/action.yaml
- .github/workflows/audit-security.yml
- .github/workflows/check-code.yml
- .github/workflows/check-dependency.yml
- .github/workflows/check-toml.yml
Signed-off-by: Xuanwo <github@xuanwo.io>
Fix https://github.com/engula/engula/issues/176
> ci: Add cargo-cache

- Cargo.lock
- Cargo.toml
- bin/engula.rs
- examples/hash_engine.rs
- src/journal/src/grpc/error.rs
- src/journal/src/grpc/journal.rs
- src/journal/src/grpc/mod.rs
- src/kernel/src/grpc/client.rs
- src/kernel/src/grpc/compose.rs
- src/kernel/src/grpc/error.rs
- src/kernel/src/grpc/kernel.proto
- src/kernel/src/grpc/kernel.rs
- src/kernel/src/grpc/mod.rs
- src/kernel/src/grpc/server.rs
- src/kernel/src/local/kernel.rs
- src/kernel/src/local/mod.rs
- src/storage/src/grpc/error.rs
- src/storage/src/grpc/mod.rs
- src/storage/src/grpc/storage.rs
> bin,kernel: add cmd to start binary server

- Cargo.lock
- Cargo.toml
- README.md
- src/engine/hash/Cargo.toml
- src/journal/Cargo.toml
- src/kernel/Cargo.toml
- src/storage/Cargo.toml
The release branch uses the current version number and the main branch should use the next version number.
> Update README and bump versions

- Cargo.lock
- Cargo.toml
- src/engine/luna/Cargo.toml
- src/engine/luna/src/collection.rs
- src/engine/luna/src/database.rs
- src/engine/luna/src/error.rs
- src/engine/luna/src/lib.rs
Discussion: https://github.com/engula/engula/discussions/195
The provided implementation in this PR is just for demonstration purposes.
BTW, I'd like to promote the engine layer from `engula::engine::xxx` to `engula::xxx`, which is simpler for engine users.
> luna: add some basic APIs

- docs/dev/release-guide.md
Closes #205 
Keep it simple for now.
> docs: add a release guide

- .github/workflows/check-code.yml
- Cargo.lock
- Cargo.toml
- bin/engula.rs
- src/kernel/src/lib.rs
> bin: support parse localhost

- src/engine/luna/src/table/block_iter.rs
- src/engine/luna/src/table/mod.rs
> luna: add block iterator

- src/futures/src/io/random/read.rs
- src/futures/src/io/random/read_ext.rs
- src/storage/src/local/mem/mod.rs
- src/storage/src/local/mem/storage.rs
> futures: use immutable reference for RandomRead

- src/journal/src/local/mem/journal.rs
- src/journal/src/local/mem/mod.rs
- src/journal/src/stream.rs
> journal: improve StreamReader interface

- Cargo.lock
- src/journal/Cargo.toml
- src/journal/src/lib.rs
- src/journal/src/remote/mod.rs
- src/journal/src/remote/shared/mod.rs
> journal: add shared journal API

- src/journal/src/remote/leader_based.rs
- src/journal/src/remote/mod.rs
- src/journal/src/remote/shared/journal.rs
- src/journal/src/remote/shared/mod.rs
> journal: move LeaderBasedJournal to seperate mod

- Cargo.lock
- src/engine/luna/Cargo.toml
- src/engine/luna/src/codec.rs
- src/engine/luna/src/database.rs
- src/engine/luna/src/error.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/write_batch.rs
Closes #297 
The decoding of `WriteBatch` is left to #299.
> luna: implement WriteBatch

- src/engine/luna/src/database.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/mem_table.rs
- src/engine/luna/src/version.rs
- src/engine/luna/src/write_batch.rs
Closes #300
This PR is based on #298.
The `MemTableScanner` is left to #302.
> luna: implement MemTable

- src/engine/luna/src/database.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/memtable.rs
- src/engine/luna/src/options.rs
- src/engine/luna/src/store.rs
- src/engine/luna/src/version.rs
> luna: add Store to manage an LSM-Tree

- src/journal/src/remote/shared/journal.rs
- src/journal/src/remote/shared/master.rs
- src/journal/src/remote/shared/mod.rs
- src/journal/src/remote/shared/orchestrator.rs
- src/journal/src/remote/shared/segment.rs
> journal: add trait of shared journal master, segment reader & writer

- src/engine/luna/src/table/mod.rs
- src/engine/luna/src/table/table_builder.rs
- src/engine/luna/src/table/table_reader.rs
> luna: replace AsyncWrite with SequentialWrite

- Cargo.lock
- rust-toolchain.toml
- src/engine/luna/Cargo.toml
- src/engine/luna/src/codec.rs
- src/engine/luna/src/database.rs
- src/engine/luna/src/error.rs
- src/engine/luna/src/flush_scheduler.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/memtable.rs
- src/engine/luna/src/options.rs
- src/engine/luna/src/store.rs
- src/engine/luna/src/table/mod.rs
- src/engine/luna/src/table/table_builder.rs
- src/engine/luna/src/version.rs
> luna: add FlushScheduler to flush memtables

- src/engine/luna/src/codec.rs
- src/engine/luna/src/flush_scheduler.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/memtable.rs
- src/engine/luna/src/merging_scanner.rs
- src/engine/luna/src/scan.rs
- src/engine/luna/src/store.rs
- src/engine/luna/src/version.rs
> luna: implement MemtableScanner

- src/engine/luna/src/codec.rs
- src/engine/luna/src/flush_scheduler.rs
- src/engine/luna/src/level.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/store.rs
- src/engine/luna/src/table/table_builder.rs
- src/engine/luna/src/version.rs
> luna: implement LevelScanner

- src/engine/luna/src/base_version.rs
- src/engine/luna/src/level.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/version.rs
> luna: implement BaseScanner

- src/engine/luna/src/codec.rs
- src/engine/luna/src/database.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/memtable.rs
- src/engine/luna/src/scanner.rs
- src/engine/luna/src/store.rs
- src/engine/luna/src/version.rs
> luna: implement InternalScanner and Scanner

- src/engine/luna/src/codec.rs
- src/engine/luna/src/level.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/store.rs
- src/engine/luna/src/table/block_reader.rs
- src/engine/luna/src/table/block_scanner.rs
- src/engine/luna/src/table/table_reader.rs
- src/engine/luna/src/table/table_scanner.rs
> luna: add Comparator

- src/engine/luna/src/base_version.rs
- src/engine/luna/src/level.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/memtable.rs
- src/engine/luna/src/store.rs
- src/engine/luna/src/version.rs
> luna: fix get API

- src/engine/luna/src/codec.rs
- src/engine/luna/src/database.rs
- src/engine/luna/src/lib.rs
- src/engine/luna/src/options.rs
- src/engine/luna/src/write_batch.rs
- src/kernel/src/local/update_writer.rs
> luna: finish WriteBatch decoding

- src/engine/luna/src/codec.rs
- src/engine/luna/src/database.rs
- src/engine/luna/src/flush_scheduler.rs
- src/engine/luna/src/memtable.rs
- src/engine/luna/src/store.rs
- src/journal/src/local/mem/journal.rs
- src/journal/src/local/mem/mod.rs
- src/journal/src/remote/shared/stream_reader.rs
- src/journal/src/stream.rs
> luna: record WriteBatch sequence for recovery

- README.md
> Update README to reflect the new design

- .github/workflows/ci.yml
- .gitmodules
- Cargo.lock
- Cargo.toml
- tools/ci/licenserc.yml
> apis: add engula-apis as a submodule

- Cargo.lock
- Cargo.toml
- src/client/Cargo.toml
- src/client/examples/universe.rs
- src/client/src/collection.rs
- src/client/src/database.rs
- src/client/src/error.rs
- src/client/src/lib.rs
- src/client/src/universe.rs
- src/client/src/universe_client.rs
> client: implement the Universe client

- Cargo.lock
- Cargo.toml
- src/server/Cargo.toml
- src/server/src/database.rs
- src/server/src/error.rs
- src/server/src/lib.rs
- src/server/src/standalone.rs
- src/server/src/supervisor.rs
- src/server/src/universe.rs
> server: add Supervisor and implement the Universe service

- src/client/examples/collection.rs
- src/client/src/collection.rs
- src/client/src/database.rs
- src/client/src/object.rs
- src/client/src/types/int64.rs
- src/client/src/types/mod.rs
Add some basic interfaces for transactions.
> client: add some interfaces

- README.md
- rust-toolchain.toml
- src/client/examples/collection.rs
- src/client/src/collection.rs
- src/client/src/database.rs
- src/client/src/expr/call_expr.rs
- src/client/src/expr/mod.rs
- src/client/src/expr/value.rs
- src/client/src/lib.rs
- src/client/src/object.rs
- src/client/src/txn_client.rs
- src/client/src/universe.rs
- src/client/src/universe_client.rs
- src/server/src/database.rs
> client: add interfaces for generic objects

- README.md
- src/client/examples/collection.rs
- src/client/src/expr/call_expr.rs
- src/client/src/object.rs
- src/server/src/cooperator.rs
- src/server/src/lib.rs
- src/server/src/standalone.rs
- src/server/src/transactor.rs
> server: implement the Txn service

- src/client/examples/collection.rs
- src/client/src/collection.rs
- src/client/src/lib.rs
- src/client/src/object.rs
> client: support collection-level transaction

- src/client/examples/collection.rs
- src/client/examples/database.rs
- src/client/src/collection.rs
- src/client/src/expr/call_expr.rs
- src/client/src/expr/mod.rs
- src/client/src/expr/value.rs
- src/client/src/object.rs
- src/client/src/txn.rs
- src/client/src/txn_client.rs
- src/server/src/transactor.rs
Make the interfaces more similar to standard collections.
> client: simplify collection and transaction interfaces

- src/client/examples/collection.rs
- src/client/examples/database.rs
- src/client/examples/universe.rs
- src/client/src/collection.rs
- src/client/src/database.rs
- src/client/src/error.rs
- src/client/src/expr/macros.rs
- src/client/src/expr/mod.rs
- src/client/src/expr/simple.rs
- src/client/src/object.rs
- src/client/src/txn.rs
- src/client/src/types/int64.rs
- src/client/src/types/mod.rs
- src/client/src/value.rs
> client: support typed collection

- src/client/examples/database.rs
- src/client/examples/int64.rs
- src/client/examples/universe.rs
- src/server/src/transactor.rs
> server: support numeric operations

- src/client/examples/list.rs
- src/client/src/expr/call_expr.rs
- src/client/src/expr/simple.rs
- src/client/src/expr/subcall_expr.rs
- src/client/src/object.rs
- src/client/src/typed.rs
- src/client/src/types/list.rs
- src/server/src/transactor.rs
> client/server: support more list operations

- src/client/examples/blob.rs
- src/client/examples/list.rs
- src/client/src/expr/call_expr.rs
- src/client/src/lib.rs
- src/client/src/typed.rs
- src/client/src/types/blob.rs
- src/server/src/transactor.rs
> client: support blob objects

- src/client/examples/unordered_map.rs
- src/client/src/lib.rs
- src/client/src/typed.rs
- src/client/src/types/mod.rs
- src/client/src/types/unordered_map.rs
- src/server/src/transactor.rs
> Support unordered map objects

- src/client/examples/map.rs
- src/client/src/any.rs
- src/client/src/lib.rs
- src/client/src/object.rs
- src/client/src/txn.rs
- src/client/src/types/blob.rs
- src/client/src/types/int64.rs
- src/client/src/types/list.rs
- src/client/src/types/map.rs
- src/client/src/types/mod.rs
> client: add typed object transaction notations

- README.md
- docs/design.md
- docs/images/architecture.drawio.svg
- docs/images/cooperator-architecture.drawio.svg
- docs/images/object-engine-architecture.drawio.svg
Rename some components to better reflect their roles and avoid confusions:
- StreamStore to StreamEngine
- EngineStore to ObjectEngine
- BlobStore to FileStore
> docs: improve the design

- Cargo.lock
- Cargo.toml
- src/object-engine/client/examples/engine.rs
- src/object-engine/client/src/bucket.rs
- src/object-engine/client/src/tenant.rs
- src/object-engine/master/Cargo.toml
- src/object-engine/master/src/error.rs
- src/object-engine/master/src/lib.rs
- src/object-engine/master/src/master.rs
- src/object-engine/master/src/server.rs
- src/object-engine/proto/proto/master.proto
> object-engine: add basic master implementation

- Cargo.lock
- Cargo.toml
- src/supervisor/Cargo.toml
- src/supervisor/src/error.rs
- src/supervisor/src/lib.rs
- src/supervisor/src/server.rs
- src/supervisor/src/supervisor.rs
> supervisor: use a standalone crate

- Cargo.lock
- src/engula/Cargo.toml
- src/engula/src/server.rs
> cmd: integrate object engine master service

- Cargo.lock
- src/object-engine/client/Cargo.toml
- src/object-engine/client/src/bucket.rs
- src/object-engine/client/src/bucket_txn.rs
> object-engine: add bucket interfaces

- Cargo.lock
- src/stream-engine/master/Cargo.toml
- src/stream-engine/master/src/server.rs
- src/stream-engine/proto/proto/master.proto
> stream-engine: add more master service interfaces

- Cargo.lock
- src/engula/Cargo.toml
- src/engula/src/server.rs
- src/supervisor/Cargo.toml
- src/supervisor/build.rs
- src/supervisor/engula/supervisor/v1/supervisor.proto
- src/supervisor/src/apis.rs
- src/supervisor/src/error.rs
- src/supervisor/src/lib.rs
- src/supervisor/src/server.rs
- src/supervisor/src/universe.rs
- src/transactor/src/server.rs
> supervisor: add interface definitions

- src/stream-engine/master/src/error.rs
- src/stream-engine/master/src/lib.rs
- src/stream-engine/master/src/master.rs
- src/stream-engine/master/src/server.rs
- src/stream-engine/master/src/stream.rs
- src/stream-engine/proto/proto/master.proto
- src/stream-engine/proto/src/lib.rs
> stream-engine: add in-memory master service implementation

- Cargo.lock
- src/client/Cargo.toml
> client: remove unused dependencies

- Cargo.lock
- src/stream-engine/client/Cargo.toml
- src/stream-engine/client/examples/engine.rs
- src/stream-engine/client/src/lib.rs
- src/stream-engine/client/src/stream.rs
> stream-engine: add APIs

- .github/workflows/ci.yml
For example, https://github.com/engula/engula/pull/457.
> ci: deps may change with .rs modifications only

- Cargo.lock
- src/stream-engine/common/Cargo.toml
- src/stream-engine/common/src/entry.rs
- src/stream-engine/common/src/lib.rs
- src/stream-engine/proto/Cargo.toml
- src/stream-engine/proto/proto/store.proto
- src/stream-engine/proto/src/cast.rs
- src/stream-engine/proto/src/lib.rs
- src/stream-engine/store/src/lib.rs
- src/stream-engine/store/src/server.rs
> stream-engine: add segment store memory implementation

- src/client/examples/tutorial.rs
> client: add a tutorial example

- README.md
- docs/design.md
- docs/images/object-engine-architecture.drawio.svg
- docs/images/object-engine-file-ingestion.drawio.svg
- docs/object-engine.md
> docs: add some detailed design for the object engine

- Cargo.lock
- src/stream-engine/client/Cargo.toml
- src/stream-engine/client/src/store/client.rs
- src/stream-engine/client/src/store/mod.rs
- src/stream-engine/client/src/store/transport.rs
- src/stream-engine/proto/proto/store.proto
- src/stream-engine/store/Cargo.toml
- src/stream-engine/store/src/lib.rs
- src/stream-engine/store/src/server.rs
> stream-engine: add store client

- Cargo.lock
- src/engula/Cargo.toml
- src/engula/src/server.rs
This closes #483.
On the fly it supports addrs with any hostname.
> server: handling ctrl-c signal

- Cargo.lock
- Cargo.toml
- src/object-engine/lsmstore/Cargo.toml
- src/object-engine/lsmstore/src/lib.rs
- src/object-engine/lsmstore/src/table/block_builder.rs
- src/object-engine/lsmstore/src/table/mod.rs
> object-engine: add block builder

- Cargo.lock
- src/object-engine/lsmstore/Cargo.toml
- src/object-engine/lsmstore/src/lib.rs
- src/object-engine/lsmstore/src/table/block_builder.rs
- src/object-engine/lsmstore/src/table/block_handle.rs
- src/object-engine/lsmstore/src/table/table_builder.rs
> object-engine: add table builder

- src/object-engine/common/src/error.rs
- src/object-engine/lsmstore/src/lib.rs
- src/object-engine/lsmstore/src/table/mod.rs
- src/object-engine/lsmstore/src/table/table_builder.rs
- src/object-engine/lsmstore/src/table/table_footer.rs
- src/object-engine/lsmstore/src/table/table_reader.rs
> object-engine: add table reader

- src/object-engine/lsmstore/src/table/block_iter.rs
- src/object-engine/lsmstore/src/table/mod.rs
> object-engine: add block iterator

- docs/dev/release-guide.md
> Update the release guide

- src/object-engine/master/proto/master.proto
- src/object-engine/master/src/server.rs
> object-engine: add file ingestion APIs

- src/stream-engine/client/src/group/io.rs
- src/stream-engine/client/src/policy/mod.rs
- src/stream-engine/client/src/reader/mod.rs
- src/stream-engine/client/src/reader/segment.rs
- src/stream-engine/client/src/reader/stream.rs
- src/stream-engine/client/src/store/batch.rs
- src/stream-engine/client/src/store/mod.rs
> stream-engine: add stream reader

- src/engula/cooperator/src/lib.rs
- src/engula/cooperator/src/write_cache.rs
> cooperator: add basic write cache structure

- Cargo.lock
- src/stream-engine/client/Cargo.toml
- src/stream-engine/client/examples/engine.rs
- src/stream-engine/client/examples/journal.rs
- src/stream-engine/client/src/core/message.rs
- src/stream-engine/client/src/core/stream.rs
- src/stream-engine/client/src/engine.rs
- src/stream-engine/client/src/group/io.rs
- src/stream-engine/client/src/group/mod.rs
- src/stream-engine/client/src/group/stream.rs
- src/stream-engine/client/src/group/worker.rs
- src/stream-engine/client/src/lib.rs
- src/stream-engine/client/src/master/stream.rs
- src/stream-engine/client/src/master/tenant.rs
- src/stream-engine/client/src/reader/segment.rs
- src/stream-engine/client/src/reader/stream.rs
- src/stream-engine/client/src/stream.rs
- src/stream-engine/client/src/tenant.rs
- src/stream-engine/master/Cargo.toml
- src/stream-engine/master/examples/master.rs
- src/stream-engine/master/src/lib.rs
- src/stream-engine/master/src/master.rs
- src/stream-engine/master/src/server.rs
- src/stream-engine/master/src/stream.rs
- src/stream-engine/store/Cargo.toml
- src/stream-engine/store/examples/store.rs
- src/stream-engine/store/src/server.rs
> stream-engine: integrate engine and worker

- src/object-engine/client/src/bucket.rs
- src/object-engine/client/src/engine.rs
- src/object-engine/client/src/lib.rs
- src/object-engine/client/src/master.rs
- src/object-engine/client/src/tenant.rs
- src/object-engine/master/proto/ingest.proto
- src/object-engine/master/src/lib.rs
- src/object-engine/master/src/server.rs
> object-engine: support local and remote modes

- Cargo.lock
- src/object-engine/client/src/engine.rs
- src/object-engine/client/src/master.rs
- src/object-engine/filestore/src/local/store.rs
- src/object-engine/filestore/src/local/tenant.rs
- src/object-engine/filestore/src/store.rs
- src/object-engine/master/Cargo.toml
- src/object-engine/master/src/fs.rs
- src/object-engine/master/src/master.rs
- src/object-engine/master/src/server.rs
> object-engine: integrate filestore with master

- Cargo.lock
- src/object-engine/client/Cargo.toml
- src/object-engine/common/Cargo.toml
- src/object-engine/filestore/Cargo.toml
- src/object-engine/lsmstore/Cargo.toml
- src/object-engine/master/Cargo.toml
Fix the problem described in #504.
> object-engine: update crate descriptions

- Cargo.lock
- src/engula/client/tests/it/main.rs
- src/engula/engula/Cargo.toml
- src/engula/engula/src/main.rs
- src/engula/engula/src/object_engine.rs
- src/engula/engula/src/server.rs
- src/object-engine/common/src/error.rs
> object-engine: add command to start the master

- Cargo.lock
- src/object-engine/client/Cargo.toml
- src/object-engine/client/src/bulkload.rs
- src/object-engine/client/src/engine.rs
- src/object-engine/client/src/file_builder.rs
- src/object-engine/client/src/lib.rs
- src/object-engine/client/src/master.rs
- src/object-engine/client/src/tenant.rs
- src/object-engine/master/proto/engine.proto
- src/object-engine/master/src/lib.rs
- src/object-engine/master/src/master.rs
> object-engine/client: integrate with lsmstore and filestore

- src/object-engine/lsmstore/src/lib.rs
- src/object-engine/lsmstore/src/table/block_iter.rs
- src/object-engine/lsmstore/src/table/format.rs
- src/object-engine/lsmstore/src/table/mod.rs
- src/object-engine/lsmstore/src/table/table_builder.rs
- src/object-engine/lsmstore/src/table/table_reader.rs
> object-engine/lsmstore: add key format with timestamp and value type

- src/object-engine/client/src/bulkload.rs
- src/object-engine/client/src/file_builder.rs
- src/object-engine/client/src/lib.rs
- src/object-engine/client/src/sst_builder.rs
- src/object-engine/lsmstore/src/table/format.rs
- src/object-engine/lsmstore/src/table/table_builder.rs
> object-engine/client: implement sst builder

- docs/images/stream-engine-data-path.drawio.svg
- docs/images/stream-engine-segments.drawio.svg
- docs/stream-engine.md
This PR closes #537.
The rendered version: [stream-engine](https://github.com/w41ter-l/engula/blob/design_doc/docs/stream-engine.md)
> docs: add stream engine design

- src/object-engine/lsmstore/src/bucket_iter.rs
- src/object-engine/lsmstore/src/store.rs
> object-engine/lsmstore: add read interfaces

- src/stream-engine/client/examples/journal.rs
- src/stream-engine/master/examples/master.rs
- src/stream-engine/master/src/master.rs
- src/stream-engine/master/src/server.rs
- src/stream-engine/store/examples/store.rs
This closes #538.
cc @w41ter-l @huachaohuang 
I'm glad to add tests if required, but I don't find a place to add cases.
> stream-engine-master: support list streams 

- Cargo.lock
- src/stream-engine/master/Cargo.toml
- src/stream-engine/master/src/master.rs
- src/stream-engine/master/src/server.rs
> stream-engine-master: support list tenants

- src/object-engine/client/src/bucket.rs
- src/object-engine/client/src/bulkload.rs
- src/object-engine/client/src/engine.rs
- src/object-engine/client/src/env/local.rs
- src/object-engine/client/src/env/mod.rs
- src/object-engine/client/src/env/remote.rs
- src/object-engine/client/src/tenant.rs
- src/object-engine/master/proto/bucket.proto
- src/object-engine/master/proto/ingest.proto
- src/object-engine/master/proto/master.proto
- src/object-engine/master/proto/tenant.proto
- src/object-engine/master/src/bucket.rs
- src/object-engine/master/src/master.rs
- src/object-engine/master/src/server.rs
- src/object-engine/master/src/tenant.rs
Merged requests into a single request union.
> object-engine: refactor master/client protocol

- src/engula/client/examples/i64_v1.rs
- src/engula/client/src/lib.rs
- src/engula/client/src/v1/client.rs
- src/engula/client/src/v1/collection.rs
- src/engula/client/src/v1/database.rs
- src/engula/client/src/v1/error.rs
- src/engula/client/src/v1/txn.rs
- src/engula/client/src/v1/types/i64.rs
- src/engula/client/src/v1/types/mod.rs
- src/engula/client/src/v1/types/numeric.rs
- src/engula/client/src/v1/universe.rs
> engula/client: add new I64 interfaces

- src/engula/client/examples/i64_v1.rs
- src/engula/client/src/v1/client.rs
- src/engula/client/src/v1/collection.rs
- src/engula/client/src/v1/error.rs
- src/engula/client/src/v1/mod.rs
- src/engula/client/src/v1/txn.rs
- src/engula/client/src/v1/types/any.rs
- src/engula/client/src/v1/types/blob.rs
- src/engula/client/src/v1/types/call.rs
- src/engula/client/src/v1/types/expr.rs
- src/engula/client/src/v1/types/i64.rs
- src/engula/client/src/v1/types/mod.rs
- src/engula/client/src/v1/universe.rs
> engula/client: add new Blob interfaces

- src/README.md
Add some brief descriptions about the source code structure.
> docs: add source code development guide

- src/engula/client/examples/list_v1.rs
- src/engula/client/src/v1/mod.rs
- src/engula/client/src/v1/types/call.rs
- src/engula/client/src/v1/types/list.rs
- src/engula/client/src/v1/types/mod.rs
> engula/client: add new list interfaces

- src/engula/client/examples/blob_v1.rs
- src/engula/client/examples/i64_v1.rs
- src/engula/client/examples/map_v1.rs
- src/engula/client/src/v1/collection.rs
- src/engula/client/src/v1/mod.rs
- src/engula/client/src/v1/types/any.rs
- src/engula/client/src/v1/types/blob.rs
- src/engula/client/src/v1/types/call.rs
- src/engula/client/src/v1/types/expr.rs
- src/engula/client/src/v1/types/i64.rs
- src/engula/client/src/v1/types/list.rs
- src/engula/client/src/v1/types/map.rs
- src/engula/client/src/v1/types/mod.rs
> engula/client: add new Map interfaces

- src/engula/client/src/v1/client.rs
- src/engula/client/src/v1/collection.rs
- src/engula/client/src/v1/txn.rs
- src/engula/client/src/v1/types/f64.rs
- src/engula/client/src/v1/types/mod.rs
> engula/client: add new F64 interfaces

- src/engula/client/examples/text_v1.rs
- src/engula/client/src/v1/mod.rs
- src/engula/client/src/v1/types/mod.rs
- src/engula/client/src/v1/types/text.rs
> engula/client: add new Text interfaces

- src/engula/client/examples/blob_v1.rs
- src/engula/client/examples/list_v1.rs
- src/engula/client/examples/set_v1.rs
- src/engula/client/examples/text_v1.rs
- src/engula/client/src/v1/collection.rs
- src/engula/client/src/v1/mod.rs
- src/engula/client/src/v1/types/any.rs
- src/engula/client/src/v1/types/blob.rs
- src/engula/client/src/v1/types/call.rs
- src/engula/client/src/v1/types/list.rs
- src/engula/client/src/v1/types/mod.rs
- src/engula/client/src/v1/types/set.rs
- src/engula/client/src/v1/types/text.rs
> engula/client: add new Set interfaces

- Cargo.lock
- src/kernel/common/src/error.rs
- src/kernel/cooperator/Cargo.toml
- src/kernel/supervisor/Cargo.toml
- src/kernel/supervisor/src/v1/mod.rs
- src/kernel/supervisor/src/v1/supervisor.rs
- src/kernel/transactor/Cargo.toml
- src/kernel/transactor/src/lib.rs
- src/kernel/transactor/src/v1/mod.rs
- src/kernel/transactor/src/v1/server.rs
- src/kernel/transactor/src/v1/transactor.rs
> kernel/transactor: integrate with the new supervisor

- src/kernel/cooperator/build.rs
- src/kernel/cooperator/engula/cooperator/v1alpha/cooperator.proto
- src/kernel/cooperator/engula/v1alpha
- src/kernel/cooperator/src/v1/apis.rs
- src/kernel/cooperator/src/v1/cooperator.rs
- src/kernel/cooperator/src/v1/mod.rs
- src/kernel/cooperator/src/v1/server.rs
- src/kernel/transactor/src/v1/transactor.rs
> kernel/cooperator: add new interface definitions

- src/client/examples/i64_v1.rs
- src/kernel/cooperator/src/v1/args.rs
- src/kernel/cooperator/src/v1/collection.rs
- src/kernel/cooperator/src/v1/cooperator.rs
- src/kernel/cooperator/src/v1/database.rs
- src/kernel/cooperator/src/v1/universe.rs
- src/kernel/cooperator/src/v1/write_batch.rs
- src/kernel/supervisor/src/v1/supervisor.rs
- src/kernel/transactor/src/v1/server.rs
- src/kernel/transactor/src/v1/transactor.rs
> kernel/cooperator: handle any and i64 type expressions

- src/client/examples/any.rs
- src/client/examples/blob_v1.rs
- src/client/src/v1/types/map.rs
- src/client/src/v1/types/set.rs
- src/kernel/cooperator/src/v1/collection.rs
> kernel/cooperator: handle blob type expression

- src/client/examples/list_v1.rs
- src/client/src/v1/types/blob.rs
- src/client/src/v1/types/list.rs
- src/client/src/v1/types/map.rs
- src/client/src/v1/types/set.rs
- src/client/src/v1/types/text.rs
- src/kernel/cooperator/src/v1/collection.rs
> kernel/cooperator: handle list type expression

- src/client/examples/list_v1.rs
- src/client/examples/map_v1.rs
- src/kernel/cooperator/src/v1/collection.rs
> kernel/cooperator: handle map type expression

- src/client/examples/universe.rs
- src/kernel/supervisor/src/apis.rs
- src/kernel/supervisor/src/supervisor.rs
- src/kernel/supervisor/src/universe.rs
- src/kernel/transactor/src/server.rs
- src/kernel/transactor/src/transactor.rs
> kernel/supervisor: implement delete database/collection

- Cargo.lock
- src/client/examples/universe.rs
- src/client/src/database.rs
- src/client/src/universe.rs
- src/kernel/supervisor/Cargo.toml
- src/kernel/supervisor/src/apis.rs
- src/kernel/supervisor/src/supervisor.rs
- src/kernel/supervisor/src/universe.rs
> kernel/supervisor: implement list databases/collections

- Cargo.lock
- src/stream-engine/common/Cargo.toml
- src/stream-engine/common/src/error.rs
- src/stream-engine/proto/proto/store-meta.proto
- src/stream-engine/proto/proto/store.proto
- src/stream-engine/store/src/lib.rs
- src/stream-engine/store/src/log/engine.rs
- src/stream-engine/store/src/log/manager.rs
- src/stream-engine/store/src/log/mod.rs
- src/stream-engine/store/src/log/reader.rs
- src/stream-engine/store/src/log/writer.rs
- src/stream-engine/store/src/opt.rs
This PR is based on #632, it closes #633.
> stream-engine/store: add log engine & file manager

- src/stream-engine/client/src/master/stream.rs
- src/stream-engine/client/src/store/client.rs
- src/stream-engine/client/src/store/transport.rs
- src/stream-engine/common/src/error.rs
- src/stream-engine/proto/proto/store.proto
- src/stream-engine/store/Cargo.toml
- src/stream-engine/store/examples/store.rs
- src/stream-engine/store/src/db/mod.rs
- src/stream-engine/store/src/db/partial_stream.rs
- src/stream-engine/store/src/db/pipeline.rs
- src/stream-engine/store/src/db/reader.rs
- src/stream-engine/store/src/db/stream_db.rs
- src/stream-engine/store/src/fs/layout.rs
- src/stream-engine/store/src/lib.rs
- src/stream-engine/store/src/log/manager.rs
- src/stream-engine/store/src/server.rs
> stream-engine-store: add partial stream & pipeline writer

- src/engine/src/db.rs
- src/server/src/cmd/del.rs
- src/server/src/cmd/mod.rs
> feat: Support del command

- src/stream-engine/store/src/log/mod.rs
- src/stream-engine/store/src/log/reader.rs
- src/stream-engine/store/src/log/writer.rs
> stream-engine/store: fix zero record header

- src/stream-engine/proto/build.rs
- src/stream-engine/proto/proto/store-manifest.proto
- src/stream-engine/proto/proto/store.proto
- src/stream-engine/proto/src/lib.rs
- src/stream-engine/store/src/db/partial_stream.rs
- src/stream-engine/store/src/db/stream_db.rs
- src/stream-engine/store/src/db/version.rs
- src/stream-engine/store/src/lib.rs
- src/stream-engine/store/src/server.rs
- src/stream-engine/store/src/sync/atomic_arc.rs
- src/stream-engine/store/src/sync/mod.rs
> stream-engine-store: add manifest

- Cargo.lock
- src/bin/src/server.rs
- src/server/Cargo.toml
- src/server/src/lib.rs
- src/server/src/mio/connection.rs
- src/server/src/mio/mod.rs
- src/server/src/mio/server.rs
- src/server/src/uio/connection.rs
- src/server/src/uio/io.rs
> Add mio based server

- src/server/src/uio/listener.rs
The address of the `addr` and `addrlen` can be changed when the listener is moved, which will cause segment fault.
Since we don't use those fields so far, we can simply remove them. If we need to get the socket address in the future, we can boxed the fields instead.
> server: fix segment fault

- src/bin/src/server.rs
- src/server/src/config.rs
- src/server/src/mio/connection.rs
- src/server/src/mio/server.rs
- src/server/src/uio/connection.rs
- src/server/src/uio/io.rs
- src/server/src/uio/server.rs
This closes #664.
We check whether a connection is timeout on each tick.
I notice some common logic between the mio impl and uio impl. Possibly @zojw you may also be interested to factor out some shared code.
cc @huachaohuang
> feat: support connection timeout 

- .editorconfig
- .github/workflows/ci.yml
- src/main.rs
- tools/ci/licenserc.yml
> ci: setup workflow

- Cargo.lock
- Cargo.toml
- src/api/Cargo.toml
- src/api/build.rs
- src/api/engula/v1/admin.proto
- src/api/engula/v1/store.proto
- src/api/src/lib.rs
- src/client/Cargo.toml
- src/client/src/lib.rs
> api: add public API definition

- Cargo.lock
- src/bin/Cargo.toml
- src/bin/src/main.rs
- src/server/src/bootstrap.rs
- src/server/src/node/group_engine.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/node/state_engine.rs
- src/server/src/service/node.rs
- src/server/src/service/root.rs
> server: join cluster

- Cargo.lock
- src/api/engula/server/v1/root.proto
- src/api/engula/v1/engula.proto
- src/server/Cargo.toml
- src/server/src/bootstrap.rs
- src/server/src/error.rs
- src/server/src/lib.rs
- src/server/src/node/group_engine.rs
- src/server/src/node/mod.rs
- src/server/src/node/route_table.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/src/root/store.rs
- src/server/src/service/node.rs
- src/server/src/service/root.rs
ref #708, Bootstrap `_system_` database with 5 bootstrapping  collections:
- collection
- meta
- database
- node
- group
Then export some `Admin()` implements based on those collections.
> root: add root schema bootstrap

- Cargo.lock
- src/bin/src/main.rs
- src/server/Cargo.toml
- src/server/src/bootstrap.rs
- src/server/src/lib.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/mod.rs
- src/server/src/node/replica/raft/mod.rs
- src/server/src/node/replica/raft/state.rs
- src/server/src/node/route_table.rs
- src/server/src/root/mod.rs
- src/server/src/service/mod.rs
- src/server/src/service/root.rs
- src/server/tests/bootstrap_test.rs
According to the opinions communicated with @zojw , the root bootstrap has been modified.
1. Poll if the node has a root replica
2. Poll if the root replica is the leader
> server: poll root replica and root leader

- Cargo.lock
- src/api/engula/server/v1/node.proto
- src/api/engula/server/v1/root.proto
- src/client/src/lib.rs
- src/client/src/node_client.rs
- src/server/Cargo.toml
- src/server/proto/v1/raft.proto
- src/server/src/bootstrap.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/node/replica/mod.rs
- src/server/src/node/replica/raft/applier.rs
- src/server/src/node/replica/raft/facade.rs
- src/server/src/node/replica/raft/fsm.rs
- src/server/src/node/replica/raft/mod.rs
- src/server/src/node/replica/raft/node.rs
- src/server/src/node/replica/raft/storage.rs
- src/server/src/node/replica/raft/transport.rs
- src/server/src/node/replica/raft/worker.rs
- src/server/src/node/resolver.rs
- src/server/src/node/state_engine.rs
- src/server/src/service/node.rs
- src/server/src/service/raft.rs
- src/server/src/service/root.rs
- src/server/tests/bootstrap_test.rs
- src/server/tests/group_test.rs
- src/server/tests/helper/mod.rs
- src/server/tests/helper/socket.rs
This PR closes #725, closes #726.
> server: support change group replicas

- src/api/engula/server/v1/node.proto
- src/server/src/node/replica/eval/cmd_batch_write.rs
- src/server/src/node/replica/eval/mod.rs
- src/server/src/node/replica/mod.rs
- src/server/src/root/schema.rs
- src/server/src/root/store.rs
> server: batch writes in shard

- src/client/src/lib.rs
- src/client/src/root_client.rs
- src/server/src/bootstrap.rs
- src/server/src/node/resolver.rs
This refers #721. It doesn't close the issue since the significant function `watch` isn't implemented in either server or client.
> feat(client): add basic root_client

- Cargo.lock
- src/api/engula/server/v1/node.proto
- src/bin/src/main.rs
- src/server/Cargo.toml
- src/server/proto/v1/metadata.proto
- src/server/src/bootstrap.rs
- src/server/src/error.rs
- src/server/src/lib.rs
- src/server/src/node/group_engine.rs
- src/server/src/node/job/destory_replica.rs
- src/server/src/node/job/mod.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/job/mod.rs
- src/server/src/node/replica/job/purge_replica.rs
- src/server/src/node/replica/mod.rs
- src/server/src/node/route_table.rs
- src/server/src/node/state_engine.rs
- src/server/src/service/node.rs
- src/server/src/service/root.rs
- src/server/tests/bootstrap_test.rs
- src/server/tests/group_test.rs
- src/server/tests/helper/client.rs
- src/server/tests/helper/runtime.rs
> api,server: refine replica lifecycle management

- src/api/engula/server/v1/metadata.proto
- src/api/engula/server/v1/root.proto
- src/server/src/bootstrap.rs
- src/server/src/root/schema.rs
- src/server/src/root/store.rs
- src/server/src/service/root.rs
closes #746: implement report(), save addition replica_stats in group0
ref #745: refine create_collection, create initial shard for collection
also support rough watch(ref #748)
> root:  support Report() and full watch

- src/api/engula/server/v1/error.proto
- src/api/engula/server/v1/node.proto
- src/api/src/lib.rs
- src/client/src/node_client.rs
- src/server/src/error.rs
- src/server/src/node/job/report_state.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/node/replica/mod.rs
- src/server/src/node/replica/retry.rs
- src/server/src/root/store.rs
- src/server/tests/group_test.rs
> api,client,server: seperated evaluate meta and data request

- src/client/src/error.rs
- src/client/src/node_client.rs
- src/client/src/root_client.rs
- src/client/src/router.rs
- src/server/src/error.rs
This refers to https://github.com/engula/engula/issues/721#issuecomment-1156222406.
> feat(client): root_client can look up root from any node addr by get_root

- src/api/engula/server/v1/root.proto
- src/api/engula/v1/metadata.proto
- src/client/src/root_client.rs
- src/client/src/router.rs
- src/server/src/bootstrap.rs
- src/server/src/node/state_engine.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/src/root/watch.rs
- src/server/src/service/mod.rs
- src/server/src/service/root.rs
> root: support watch root change

- src/server/src/node/engine/group.rs
- src/server/src/node/replica/fsm/checkpoint.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/node/replica/raft/fsm.rs
- src/server/src/node/replica/raft/node.rs
- src/server/src/node/replica/raft/snap/apply.rs
- src/server/src/node/replica/raft/snap/create.rs
- src/server/src/node/replica/raft/snap/mod.rs
- src/server/src/node/replica/raft/storage.rs
- src/server/src/node/replica/raft/worker.rs
> server: apply snapshot

- src/server/proto/v1/metadata.proto
- src/server/proto/v1/raft.proto
- src/server/src/node/mod.rs
- src/server/src/node/replica/raft/mod.rs
- src/server/src/node/replica/raft/snap/create.rs
- src/server/src/node/replica/raft/snap/download.rs
- src/server/src/node/replica/raft/snap/mod.rs
- src/server/src/node/replica/raft/snap/send.rs
- src/server/src/node/replica/raft/transport.rs
- src/server/src/node/replica/raft/worker.rs
- src/server/src/service/raft.rs
> server: download snapshot

- src/server/src/node/replica/raft/applier.rs
- src/server/src/node/replica/raft/node.rs
- src/server/src/node/replica/raft/snap/mod.rs
- src/server/src/node/replica/raft/storage.rs
> server: recover from snapshot

- src/api/engula/server/v1/metadata.proto
- src/api/engula/v1/metadata.proto
- src/client/src/lib.rs
- src/client/src/router.rs
- src/server/src/node/engine/group.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
> feat(client): handle all update events for router

- src/server/src/node/engine/group.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/raftgroup/applier.rs
- src/server/src/raftgroup/mod.rs
- src/server/src/raftgroup/node.rs
- src/server/src/raftgroup/snap/download.rs
- src/server/src/raftgroup/snap/mod.rs
- src/server/src/raftgroup/storage.rs
- src/server/src/raftgroup/worker.rs
> server: compact log and recycle snapshots

- src/server/src/node/job/report_state.rs
- src/server/src/node/replica/eval/cmd_prefix_list.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
tiny fix to pass #781 client example test
> server: make server testable with client

- src/api/engula/server/v1/node.proto
- src/server/proto/v1/metadata.proto
- src/server/src/node/replica/mod.rs
- src/server/src/service/node.rs
> api: define migration api

- src/api/engula/server/v1/node.proto
- src/client/src/lib.rs
- src/client/src/node_client.rs
- src/server/build.rs
- src/server/src/lib.rs
- src/server/src/node/engine/group.rs
- src/server/src/node/migrate/ctrl.rs
- src/server/src/node/migrate/mod.rs
- src/server/src/node/migrate/pull.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/eval/cmd_migrate.rs
- src/server/src/node/replica/eval/cmd_prefix_list.rs
- src/server/src/node/replica/eval/mod.rs
- src/server/src/node/replica/fsm/checkpoint.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/node/replica/job/purge_replica.rs
- src/server/src/node/replica/mod.rs
- src/server/src/root/mod.rs
- src/server/src/service/node.rs
> server: pull shard chunk from src group

- src/api/engula/server/v1/node.proto
- src/server/src/lib.rs
- src/server/src/node/engine/group.rs
- src/server/src/node/engine/mod.rs
- src/server/src/node/migrate/gc.rs
- src/server/src/node/migrate/mod.rs
- src/server/src/node/replica/eval/cmd_batch_write.rs
- src/server/src/node/replica/eval/cmd_delete.rs
- src/server/src/node/replica/eval/cmd_get.rs
- src/server/src/node/replica/eval/cmd_prefix_list.rs
- src/server/src/node/replica/eval/cmd_put.rs
- src/server/src/node/replica/eval/mod.rs
- src/server/src/node/replica/mod.rs
> server: support multi-version keys

- src/server/src/node/engine/group.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/retry.rs
- src/server/src/node/shard.rs
> server: iterate within shard

- src/api/engula/server/v1/metadata.proto
- src/server/src/bootstrap.rs
- src/server/src/node/engine/group.rs
- src/server/src/node/mod.rs
- src/server/src/raftgroup/storage.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
> root: handle heartbeat

- src/client/examples/kv.rs
- src/client/src/app_client.rs
- src/client/src/error.rs
- src/client/src/retry.rs
- src/client/src/router.rs
Example can pass with #797.
This closes #787 .
> feat(client): naive retry policy

- src/client/src/app_client.rs
- src/client/src/router.rs
> client: resume watching event stream

- Cargo.lock
- src/api/engula/server/v1/metadata.proto
- src/api/engula/v1/engula.proto
- src/api/engula/v1/metadata.proto
- src/client/Cargo.toml
- src/client/examples/kv.rs
- src/client/src/app_client.rs
- src/client/src/lib.rs
- src/client/src/retry.rs
- src/client/src/root_client.rs
- src/client/src/router.rs
- src/server/src/node/shard.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/src/root/store.rs
- src/server/src/service/root.rs
closes #745
- support create hash shards
- fix some problems during testing
> *: support create collection with hash shards

- src/server/src/node/engine/group.rs
- src/server/tests/migration_test.rs
> server: local state independent WriteBatchRep

- Cargo.lock
- src/api/engula/server/v1/root.proto
- src/client/src/root_client.rs
- src/server/build.rs
- src/server/proto/v1/schedule.proto
- src/server/src/node/migrate/ctrl.rs
- src/server/src/node/replica/job/mod.rs
- src/server/src/node/replica/job/schedule.rs
- src/server/src/node/replica/mod.rs
- src/server/src/raftgroup/facade.rs
- src/server/src/raftgroup/mod.rs
- src/server/src/raftgroup/node.rs
- src/server/src/raftgroup/worker.rs
- src/server/src/root/allocator/policy_replica_cnt.rs
- src/server/src/root/mod.rs
- src/server/src/service/root.rs
> server: cure sicked raft group

- src/api/engula/server/v1/node.proto
- src/server/src/node/replica/migrate.rs
- src/server/src/node/replica/mod.rs
- src/server/src/raftgroup/facade.rs
- src/server/src/raftgroup/worker.rs
> server: support transfer leadership

- src/api/engula/server/v1/root.proto
- src/client/src/app_client.rs
- src/client/src/root_client.rs
- src/client/src/router.rs
- src/server/src/bootstrap.rs
- src/server/src/node/mod.rs
- src/server/src/node/resolver.rs
- src/server/src/root/mod.rs
- src/server/src/service/root.rs
> *: replace rpc Resolver with Router

- src/server/src/node/migrate/ctrl.rs
- src/server/src/node/mod.rs
- src/server/src/node/replica/job/mod.rs
- src/server/src/node/replica/job/purge_replica.rs
- src/server/src/node/replica/job/schedule.rs
- src/server/src/node/replica/mod.rs
- src/server/src/node/replica/state.rs
- src/server/src/raftgroup/facade.rs
- src/server/src/raftgroup/mod.rs
- src/server/src/raftgroup/worker.rs
- src/server/src/runtime/mod.rs
- src/server/src/runtime/sync.rs
> server: manage replica async jobs

- src/client/src/node_client.rs
- src/server/src/bootstrap.rs
- src/server/src/node/replica/retry.rs
- src/server/src/raftgroup/worker.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/policy_replica_cnt.rs
- src/server/src/root/allocator/policy_shard_cnt.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/allocator/source.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
> root: support balance & reallocate shards and replicas

- src/server/src/service/root.rs
> root: convert returned error from NotLeader to NotRootLeader

- src/server/src/error.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/policy_leader_cnt.rs
- src/server/src/root/allocator/policy_replica_cnt.rs
- src/server/src/root/allocator/policy_shard_cnt.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
> root: add some root diagnosis log

- Cargo.lock
- src/client/examples/kv.rs
- src/client/src/app_client.rs
- src/client/src/conn_manager.rs
- src/client/src/root_client.rs
- src/server/Cargo.toml
- src/server/src/lib.rs
- src/server/src/node/mod.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/policy_leader_cnt.rs
- src/server/src/root/allocator/policy_replica_cnt.rs
- src/server/src/root/allocator/policy_shard_cnt.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/job.rs
- src/server/src/root/mod.rs
- src/server/src/service/root.rs
- src/server/tests/admin_test.rs
- add some admin operation end2end test
- fix replica balance logic bug
balance speed still needs more improve
> root: add admin test & fix replica unbalance

- src/server/src/bootstrap.rs
- src/server/src/node/engine/group.rs
- src/server/src/node/resolver.rs
- src/server/src/raftgroup/transport.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/tests/bootstrap_test.rs
- src/server/tests/helper/client.rs
- src/server/tests/helper/context.rs
> test: restart cluster

- src/client/src/node_client.rs
- src/server/src/client.rs
- src/server/src/lib.rs
- src/server/src/node/migrate/ctrl.rs
- src/server/src/node/migrate/forward.rs
- src/server/src/node/migrate/mod.rs
- src/server/src/root/schema.rs
> root: add remote store

- src/client/src/retry.rs
- src/server/src/raftgroup/transport.rs
- src/server/src/service/raft.rs
- src/server/tests/helper/context.rs
- src/server/tests/helper/runtime.rs
- src/server/tests/rw_test.rs
> test: get/put with config change

- src/client/src/app_client.rs
- src/server/src/error.rs
- src/server/src/node/replica/mod.rs
- src/server/tests/bootstrap_test.rs
- src/server/tests/group_test.rs
- src/server/tests/helper/client.rs
- src/server/tests/helper/context.rs
- src/server/tests/rw_test.rs
> test: mutation/fetching with leader transfer

- src/server/tests/helper/client.rs
- src/server/tests/migration_test.rs
> test: abort migration

- src/server/tests/migration_test.rs
> test: migration with offline peers

- src/client/examples/kv.rs
- src/client/src/app_client.rs
- src/client/src/conn_manager.rs
- src/client/src/error.rs
- src/client/src/lib.rs
- src/client/src/root_client.rs
- src/server/src/error.rs
- src/server/tests/client_test.rs
> test: client send request to unreachable peers

- src/server/src/client.rs
- src/server/src/node/replica/schedule/mod.rs
- src/server/src/root/schema.rs
> server: clear replica state

- src/api/engula/server/v1/node.proto
- src/server/src/node/mod.rs
- src/server/src/node/replica/mod.rs
- src/server/src/root/job.rs
- src/server/src/service/node.rs
- src/server/tests/helper/client.rs
- src/server/tests/migration_test.rs
> server: collect migration state

- src/client/src/error.rs
- src/client/src/retry.rs
- src/server/src/error.rs
- src/server/tests/client_test.rs
> client: add AppError::AlreadyExists

- src/client/src/error.rs
- src/client/src/retry.rs
- src/server/src/error.rs
- src/server/src/root/mod.rs
- src/server/src/service/root.rs
> server: allocate replicas return ResourceExhausted

- src/api/engula/server/v1/error.proto
- src/api/src/error.rs
- src/client/src/error.rs
- src/client/src/group_client.rs
- src/client/src/root_client.rs
- src/client/src/router.rs
- src/server/src/error.rs
- src/server/src/node/replica/migrate.rs
- src/server/src/node/replica/mod.rs
- src/server/src/node/replica/retry.rs
- src/server/src/raftgroup/applier.rs
- src/server/src/raftgroup/node.rs
- src/server/src/root/mod.rs
- src/server/src/service/root.rs
- src/server/tests/helper/client.rs
- src/server/tests/rw_test.rs
> *: add term for NotLeader and NotRoot

- src/server/src/node/replica/retry.rs
- src/server/src/raftgroup/applier.rs
- src/server/src/raftgroup/node.rs
- src/server/src/raftgroup/worker.rs
> server: truncated proposal response NotLeader

- Cargo.lock
- Cargo.toml
- src/bin/Cargo.toml
- src/bin/bench/Cargo.toml
- src/bin/bench/src/config.rs
- src/bin/bench/src/main.rs
- src/bin/bench/src/metrics.rs
- src/bin/bench/src/worker.rs
- src/server/src/runtime/shutdown.rs
> bin: add bench tool

- scripts/server.dashboard.py
- src/bin/bench/src/main.rs
Refs #837.
Generate dashboard:
```
pip3 install grafanalib --user
generate-dashboard -o frontend.json scripts/server.dashboard.py 
```
> scripts: add server.dashboard.py

- src/server/src/node/replica/fsm/checkpoint.rs
- src/server/src/raftgroup/snap/download.rs
- src/server/src/raftgroup/snap/mod.rs
- src/server/src/raftgroup/snap/send.rs
> server: create dir before create snap files

- src/server/src/lib.rs
- src/server/src/node/replica/fsm/checkpoint.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/node/replica/mod.rs
- src/server/src/raftgroup/mod.rs
- src/server/src/raftgroup/node.rs
- src/server/src/raftgroup/storage.rs
- src/server/src/raftgroup/worker.rs
- src/server/tests/helper/context.rs
- src/server/tests/snapshot_test.rs
> test: report snap status

- scripts/server.dashboard.py
- src/server/src/root/allocator/mod.rs
- src/server/src/root/job.rs
- src/server/src/root/metrics.rs
- src/server/src/root/mod.rs
- src/server/src/root/schedule.rs
> metrics: add root related grafana script

- src/server/src/raftgroup/transport.rs
> server: reduce raftgroup unreachable log

- src/server/src/root/job.rs
- src/server/src/root/mod.rs
> root: pre-send heartbeat current node when root group updated

- src/api/engula/server/v1/metadata.proto
- src/api/engula/server/v1/node.proto
- src/api/engula/server/v1/root.proto
- src/server/src/node/job/report_state.rs
- src/server/src/root/job.rs
- src/server/src/service/node.rs
- src/server/tests/helper/client.rs
> api: add ScheduleState message and MoveReplicas rpc method

- src/client/src/group_client.rs
- src/server/proto/v1/schedule.proto
- src/server/src/error.rs
- src/server/src/root/schedule.rs
- src/server/src/service/admin/job.rs
- src/server/src/service/admin/metadata.rs
- src/server/tests/admin_test.rs
> root: use new move_replica to move replica

- src/server/src/raftgroup/storage.rs
> server: fix multiple snapshot creating

- src/client/src/app_client.rs
- src/client/src/root_client.rs
- src/server/proto/v1/schedule.proto
- src/server/src/root/bg_job.rs
- src/server/src/root/mod.rs
- src/server/src/root/schema.rs
- src/server/tests/admin_test.rs
closes #790
remain question: real shard(and its data) still need purge in future works
> *: support delete database & collection

- src/server/src/node/replica/mod.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/policy_leader_cnt.rs
- src/server/src/root/allocator/policy_replica_cnt.rs
- src/server/src/root/allocator/policy_shard_cnt.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/bg_job.rs
- src/server/src/root/collector.rs
- src/server/src/root/mod.rs
- src/server/src/root/schedule.rs
this PR makes some fix for old balancer logic
> root: fix unbalance for shard & leader

- src/client/src/error.rs
> client: unexpected transport error

- src/api/engula/server/v1/metadata.proto
- src/client/src/router.rs
- src/server/src/node/replica/fsm/mod.rs
> client: ignore staled shard group lookup

- .editorconfig
- Makefile
Add Makefile for task entrance such as build/lint/fmt/test tasks
> Add Makefile for task entrance such as build/lint

- src/server/src/raftgroup/storage.rs
> server: fix empty result when entry size over max_size limit

- src/server/src/node/migrate/ctrl.rs
one line change, just remove `.await` after spawn
> server: fix node join blocking

- src/server/src/error.rs
- src/server/src/node/replica/fsm/mod.rs
- src/server/src/node/replica/mod.rs
- src/server/src/raftgroup/facade.rs
- src/server/src/raftgroup/node.rs
- src/server/src/raftgroup/worker.rs
- src/server/src/schedule/actions/act_config_change.rs
> server: fix ignored config change

- README.md
- docs/design.md
- docs/img/architecture.drawio.svg
- docs/img/data-organization.drawio.svg
- docs/img/group-and-shard.drawio.svg
- docs/img/topology.drawio.svg
The rendered version: https://github.com/w41ter/engula/blob/main/docs/design.md
> docs: add design.md and update readme

- src/server/proto/v1/metadata.proto
- src/server/src/bootstrap.rs
- src/server/src/constants.rs
- src/server/src/lib.rs
- src/server/src/node/engine/group.rs
- src/server/src/node/engine/mod.rs
- src/server/src/node/engine/state.rs
- src/server/src/node/job/destory_replica.rs
- src/server/src/node/mod.rs
- src/server/src/node/route_table.rs
- src/server/src/raftgroup/mod.rs
- src/server/src/root/allocator/mod.rs
- src/server/src/root/allocator/policy_leader_cnt.rs
- src/server/src/root/allocator/policy_replica_cnt.rs
- src/server/src/root/allocator/policy_shard_cnt.rs
- src/server/src/root/allocator/sim_test.rs
- src/server/src/root/bg_job.rs
- src/server/src/root/collector.rs
- src/server/src/root/heartbeat.rs
- src/server/src/root/mod.rs
- src/server/src/root/schedule.rs
- src/server/src/root/schema.rs
- src/server/src/root/store.rs
> server: StateEngine replace rocksdb to raft_engine
